version: '3'

services:
  sql:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "A1!-maimed-subtype-tainted-polygraph-glorious-librarian"
      MSSQL_USER: "sa"